# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the number of points in trangles.
#' 
#' @param vertices numeric matrix with two columns: xy coordinates
#' @param faces numeric matrix with three columns: index of points which form the triangles
#' 
#' @export
#' @return a vector with number of points in each triangle
#' 
#' @references \url{https://stackoverflow.com/questions/2049582/how-to-determine-if-a-point-is-in-a-2d-triangle}
pointsInTrianglesC <- function(vertices, faces) {
    .Call('_findWeb_pointsInTrianglesC', PACKAGE = 'findWeb', vertices, faces)
}

#' Compute the number line intersections for a given web
#' 
#' @param g a web
#'  
#' @export
#' @return a vector with number of intersections for each line segment (Ingress: link)
#' 
#' @references \url{https://stackoverflow.com/questions/20519431/finding-point-of-intersection-in-r}
evaluateC <- function(g) {
    .Call('_findWeb_evaluateC', PACKAGE = 'findWeb', g)
}

